AWSTemplateFormatVersion: 2010-09-09
Description: AWS CloudFormation template to deploy app from ECR to Fargate.

Parameters:
  AppContainerPort:
    Type: Number
  DBPort:
    Type: Number

Resources:
  DemoECSTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ContainerDefinitions:
        - Name: !Sub ${AWS::StackName}-DemoContainer
          Image: ..
          PortMappings:
            - ContainerPort: !Ref AppContainerPort
              Protocol: tcp
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !ImportValue CloudWatchLogGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: demo-api
      Family: !Sub ${AWS::StackName}-DemoContainer
      Cpu: 256
      Memory: 512
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !ImportValue ECSTaskExecutionRole
      TaskRoleArn: ..
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-TaskDefinition

  DemoTaskService:
    Type: AWS::ECS::Service
    DependsOn: ALBListenerRule
    Properties:
      Cluster: !ImportValue ECSCluster
      DesiredCount: 2
      LaunchType: FARGATE
      LoadBalancers: 
        - ContainerName: !Sub ${AWS::StackName}-DemoContainer
          ContainerPort: !Ref AppContainerPort
          TargetGroupArn: !Ref ALBTargetGroup
      ServiceName: !Sub ${AWS::StackName}-ECSService
      TaskDefinition: !Ref DemoECSTaskDefinition
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumPercent: 70
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp:  DISABLED
          Subnets:
            - !ImportValue FargateSubnet1
            - !ImportValue FargateSubnet2
          SecurityGroups:
            - !ImportValue FargateTaskSG
      Tags: 
        - Key: Name
          Value: !Sub ${AWS::StackName}-DemoECSService

  ALBTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub ${AWS::StackName}-ALBTargetGroup
      Port: !Ref AppContainerPort
      HealthCheckPath: /health
      Matcher:
        HttpCode: 200-299
      HealthCheckIntervalSeconds: 10
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 5
      Protocol: HTTP
      VpcId: !ImportValue VPC
      TargetType: ip
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: '60'
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-ALBTargetGroup

  ALBListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !ImportValue Listener
      Priority: 1
      Conditions: 
        - Field: path-pattern
          Values:
            - /api/users*
      Actions:
        - TargetGroupArn: !Ref ALBTargetGroup
          Type: forward 

  DBNameParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: dbName
      Type: String
      Value: users
      Description: SSM Parameter for database name.
      AllowedPattern: "^[a-zA-Z]{1,10}$"
      Tags:
        - Key: Name
          Value: dbName

  DBUserParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: dbUserName
      Type: String
      Value: adminuser
      Description: SSM Parameter for database user.
      AllowedPattern: "^[a-zA-Z]{1,10}$"
      Tags:
        - Key: Name
          Value: dbUser

  DBPasswordParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: dbUserPassword
      Type: String
      Value: "Monday2026"
      Description: SSM Parameter for database password.
      AllowedPattern: "^[a-zA-Z]{1,15}$"
      Tags:
        - Key: Name
          Value: dbPassword

  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet Group For MySQL RDS Instance
      DBSubnetGroupName: !Sub ${AWS::StackName}-demodbsubnetgroup
      SubnetIds:
        - !ImportValue RDSSubnet1
        - !ImportValue RDSSubnet2
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-RDSSubnetGroup

  RDS:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: '20'
      BackupRetentionPeriod: 0
      DBInstanceClass: db.t2.micro
      DBInstanceIdentifier: !Sub ${AWS::StackName}-RDS
      DBName: '{{resolve:ssm:dbName:1}}'
      VPCSecurityGroups: 
        - !ImportValue RDSSG
      DBSubnetGroupName: !Ref DBSubnetGroup
      Engine: mysql 
      MasterUsername: '{{resolve:ssm:dbUserName:1}}'
      MasterUserPassword: '{{resolve:ssm:dbUserPassword:1}}'
      MultiAZ: true
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-dBInstance

  RDSLambda:
    Type: AWS::Lambda::Function 
    Properties: 
      Description: Lambda function to create a database in rds and a table 
      FunctionName: LambdaforRDS
      Role: !ImportValue LambdaExecutionRole
      Runtime: python3.11
      Handler: index.handler
      Timeout: 15
      Layers: !Sub arn:aws:lambda:${AWS::Region}:336392948345:layer:AWSSDKPandas-Python312:14
      VpcConfig:
        SecurityGroupIds:
          - !ImportValue FargateTaskSG
        SubnetIds:
          - !ImportValue FargateSubnet1
          - !ImportValue FargateSubnet2
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-LambdaforRDS
      Environment:
        Variables:
          DB_HOST: !GetAtt RDS.Endpoint.Address
      Code:
        ZipFile: |
          import pymysql
          import boto3
          import os

          def handler(event, context):
              ssm = boto3.client('ssm')
              try:
                  db_host = os.environ['DB_HOST']
                  user = ssm.get_parameter(Name='dbUserName')['Parameter']['Value']
                  pwd = ssm.get_parameter(Name='dbUserPassword')['Parameter']['Value']
                  db_name = ssm.get_parameter(Name='dbName')['Parameter']['Value']

                  print(f"Connecting to {db_host}...")
                  conn = pymysql.connect(
                      host=db_host,
                      user=user,
                      password=pwd,
                      database=db_name,
                      connect_timeout=10
                  )
                  
                  with conn.cursor() as cur:
                      cur.execute("CREATE TABLE IF NOT EXISTS users (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(255), email VARCHAR(20), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)")
                      conn.commit()
                  
                  print("Table created successfully!")
                  return {"status": "success"}

              except Exception as e:
                  print(f"Error: {str(e)}")
                  raise e

              finally:
                  if 'conn' in locals():
                      conn.close()      

Outputs:
  APIEndpoint: 
    Description: Project API Endpoint
    Value: !Join ['',['http://', !ImportValue DomainName, '/api/users']]
    Export:
      Name: ProjectAPIEndpoint
