AWSTemplateFormatVersion: 2010-09-09
Description: AWS CloudFormation template to deploy app from ECR to Fargate.

Parameters:
  AppContainerPort:
    Type: Number
  DBPort:
    Type: Number

  DatabaseName:
    Type: String
    Default: users
    Description: The database name
  
  DatabaseUser:
    Type: String
    Default: adminuser
    Description: The database admin account username
  
  DatabasePassword:
    Type: String
    Default: Monday2026!
    Description: The database admin account password
    NoEcho: true

Resources:
  DemoECSTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ContainerDefinitions:
        - Name: !Sub ${AWS::StackName}-DemoContainer
          Image: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/cluster-ecrrepo:v1
          PortMappings:
            - ContainerPort: !Ref AppContainerPort
              Protocol: tcp
          Environment:
            - Name: DB_HOST
              Value: !GetAtt RDSInstance.Endpoint.Address
            - Name: DB_USER
              Value: !Ref DatabaseUser
            - Name: DB_PASSWORD
              Value: !Ref DatabasePassword
            - Name: DB_NAME
              Value: !Ref DatabaseName
            - Name: DB_PORT
              Value: !Ref DBPort
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !ImportValue ECSTaskLogGroupName
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: demo-api
      Family: !Sub ${AWS::StackName}-DemoContainer
      Cpu: '256'
      Memory: '512'
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !ImportValue ECSTaskExecutionRole
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-TaskDefinition

  DemoTaskService:
    Type: AWS::ECS::Service
    DependsOn: 
      - ALBListenerRule
      - RunDBScripts
    Properties:
      Cluster: !ImportValue ECSCluster
      DesiredCount: 2
      LaunchType: FARGATE
      LoadBalancers: 
        - ContainerName: !Sub ${AWS::StackName}-DemoContainer
          ContainerPort: !Ref AppContainerPort
          TargetGroupArn: !Ref ALBTargetGroup
      ServiceName: !Sub ${AWS::StackName}-ECSService
      TaskDefinition: !Ref DemoECSTaskDefinition
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 70
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp:  DISABLED
          Subnets:
            - !ImportValue FargateSubnet1
            - !ImportValue FargateSubnet2
          SecurityGroups:
            - !ImportValue FargateTaskSG
      Tags: 
        - Key: Name
          Value: !Sub ${AWS::StackName}-DemoECSService

  ALBTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub ${AWS::StackName}-ALBTargetGroup
      Port: !Ref AppContainerPort
      HealthCheckPath: /health
      Matcher:
        HttpCode: 200-299
      HealthCheckIntervalSeconds: 10
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 5
      Protocol: HTTP
      VpcId: !ImportValue VPC
      TargetType: ip
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: '60'
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-ALBTargetGroup

  ALBListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !ImportValue Listener
      Priority: 1
      Conditions: 
        - Field: path-pattern
          Values:
            - /*
      Actions:
        - TargetGroupArn: !Ref ALBTargetGroup
          Type: forward 

  DBNameParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: dbName
      Type: String
      Value: !Ref DatabaseName
      Description: SSM Parameter for database name.
      AllowedPattern: "^[a-zA-Z]{1,20}$"
      Tags:
        Name: dBName

  DBUserParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: dbUserName
      Type: String
      Value: !Ref DatabaseUser
      Description: SSM Parameter for database user.
      AllowedPattern: "^[a-zA-Z]{1,10}$"
      Tags:
        Name: dBUser

  DBPasswordParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: dbUserPassword
      Type: String
      Value: !Ref DatabasePassword
      Description: SSM Parameter for database password.
      AllowedPattern: "^[a-zA-Z0-9!]{8,30}$"
      Tags:
        Name: dBPassword

  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet Group For MySQL RDS Instance
      DBSubnetGroupName: !Sub ${AWS::StackName}-demodbsubnetgroup
      SubnetIds:
        - !ImportValue RDSSubnet1
        - !ImportValue RDSSubnet2
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-RDSSubnetGroup

  RDSDBParameterGroup:
    Type: AWS::RDS::DBParameterGroup
    Properties:
      Description: Parameter group for MySQL 8.0 to use native password authentication
      Family: mysql8.0
      Parameters:
        default_authentication_plugin: mysql_native_password
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-rds-pg

  RDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: '20'
      BackupRetentionPeriod: 0
      DBInstanceClass: db.t3.micro
      DBInstanceIdentifier: !Sub ${AWS::StackName}-rds-instance
      DBName: !Ref DatabaseName
      VPCSecurityGroups: 
        - !ImportValue RDSSG
      DBSubnetGroupName: !Ref DBSubnetGroup
      DBParameterGroupName: !Ref RDSDBParameterGroup
      Engine: mysql 
      EngineVersion: "8.0.44"
      MasterUsername: !Ref DatabaseUser
      MasterUserPassword: !Ref DatabasePassword
      MultiAZ: true
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-dBInstance

  RDSLambda:
    Type: AWS::Lambda::Function 
    Properties: 
      Description: Lambda function to create a database in rds and a table 
      FunctionName: !Sub ${AWS::StackName}-LambdaforRDS
      Role: !ImportValue LambdaExecutionRole
      Runtime: python3.11
      Handler: index.handler
      Timeout: 300
      Layers: 
        - !Sub arn:aws:lambda:${AWS::Region}:770693421928:layer:Klayers-p311-pymysql:3
        - !Sub arn:aws:lambda:${AWS::Region}:770693421928:layer:Klayers-p311-cryptography:23
      VpcConfig:
        SecurityGroupIds:
          - !ImportValue FargateTaskSG
        SubnetIds:
          - !ImportValue FargateSubnet1
          - !ImportValue FargateSubnet2
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-LambdaforRDS
      Environment:
        Variables:
          DB_HOST: !GetAtt RDSInstance.Endpoint.Address
          DB_USER_PARAM: !Ref DBUserParam
          DB_PASSWORD_PARAM: !Ref DBPasswordParam
          DB_NAME_PARAM: !Ref DBNameParam
      Code:
        ZipFile: |
          import pymysql
          import boto3
          import os
          import cfnresponse

          def handler(event, context):
              print(f"RECEIVED EVENT: {event}")
              if event['RequestType'] == 'Delete':
                  cfnresponse.send(event, context, cfnresponse.SUCCESS, {})
                  return

              ssm = boto3.client('ssm')
              conn = None
              
              try:
                  db_host = os.environ['DB_HOST']
                  user_param = os.environ['DB_USER_PARAM']
                  pwd_param = os.environ['DB_PASSWORD_PARAM']
                  name_param = os.environ['DB_NAME_PARAM']

                  user = ssm.get_parameter(Name=user_param)['Parameter']['Value']
                  pwd = ssm.get_parameter(Name=pwd_param)['Parameter']['Value']
                  db_name = ssm.get_parameter(Name=name_param)['Parameter']['Value']

                  conn = pymysql.connect(
                      host=db_host,
                      user=user,
                      password=pwd,
                      database=db_name,
                      connect_timeout=10
                  )

                  with conn.cursor() as cur:
                      cur.execute(f"ALTER USER '{user}'@'%' IDENTIFIED WITH mysql_native_password BY '{pwd}';")
                      cur.execute("FLUSH PRIVILEGES;")
                      
                      cur.execute("""
                          CREATE TABLE IF NOT EXISTS users (
                              id INT AUTO_INCREMENT PRIMARY KEY, 
                              name VARCHAR(255), 
                              email VARCHAR(100), 
                              created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                          )
                      """)
                      conn.commit()
                  
                  cfnresponse.send(event, context, cfnresponse.SUCCESS, {"Message": "Table Created"})

              except Exception as e:
                  print(f"Error: {str(e)}")
                  cfnresponse.send(event, context, cfnresponse.FAILED, {"Message": str(e)})
              finally:
                  if conn: conn.close()

  RunDBScripts:
    Type: Custom::DBInitializer
    DependsOn: 
      - RDSInstance
      - RDSLambda
    Properties:
      ServiceToken: !GetAtt RDSLambda.Arn
      DBName: !Ref DBNameParam
      ServiceTimeout: 300

Outputs:
  APIEndpoint: 
    Description: Project API Endpoint
    Value: !Join ['',['http://', !ImportValue DomainName ]]
    Export:
      Name: ProjectAPIEndpoint
