AWSTemplateFormatVersion: 2010-09-09
Description: AWS CloudFormation template to define IAM roles that containers need to interact with CloudWatch and ECR.

Resources: 
  ECSTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement: 
          - Effect: Allow
            Principal: 
              Service: 
                - ecs-tasks.amazonaws.com
            Action:
              - sts.AssumeRole
      Path: /
      Policies:
        - PolicyName: !Sub ${AWS::StackName}-Policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - ecr:GetDownloadUrlForLayer
                  - ecr:BatchGetImage
                  - ecr:BatchCheckLayerAvailability
                Resource: !ImportValue ECRArn
                Condition:
                  StringEquals:
                    aws:SourceVpce: 
                      - !ImportValue VPCInterfaceEndpointECRDKR
                      - !ImportValue VPCInterfaceEndpointECRAPI

              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !ImportValue ECSTaskLogGroup
                Condition:
                  StringEquals:
                    aws:SourceVpce: !ImportValue VPCInterfaceEndpointCWLogs

              - Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                Resource: "*"
                Condition:
                  StringEquals:
                    aws:SourceVpce: 
                      - !ImportValue VPCInterfaceEndpointECRDKR
                      - !ImportValue VPCInterfaceEndpointECRAPI

              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource: !Sub 'arn:aws:s3:::prod-${AWS::Region}-starport-layer-bucket/*'
                Condition:
                  StringEquals:
                    aws:sourceVpc: !ImportValue VPC

              - Effect: Allow
                Action:
                  - ssm:GetParameter
                  - ssm:GetParameters
                Resource: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/*'
                Condition:
                  StringEquals:
                    aws:SourceVpce: !ImportValue VPCInterfaceEndpointSSM

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
      Policies:
        - PolicyName: LambdaSSMReadPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ssm:GetParameter
                  - ssm:GetParameters
                Resource: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/*'
              
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !ImportValue LambdaLogGroup
                Condition:
                  StringEquals:
                    aws:SourceVpce: !ImportValue VPCInterfaceEndpointCWLogs

Outputs:
  ECSTaskExecutionRole: 
    Description: ECS Task Execution Role
    Value: !GetAtt ECSTaskExecutionRole.Arn
    Export:
      Name: ECSTaskExecutionRole

  LamdaExecutionRole: 
    Description: Lambda Execution Role
    Value: !GetAtt LambdaExecutionRole.Arn
    Export:
      Name: LambdaExecutionRole